-- ============================================================
-- OLIST E-COMMERCE BUSINESS ANALYSIS
-- ============================================================


---------------------------------------------------------------------------
-- 01. Revenue & Order Performance
---------------------------------------------------------------------------

-- Business question:
-- What are the total number of delivered orders, total revenue,
-- and average order value (AOV)?

SELECT
    total_orders,
    total_revenue,
    ROUND((total_revenue / total_orders), 2) AS aov
FROM 
    (
        SELECT
            COUNT(DISTINCT o.order_id) AS total_orders, 
            SUM(price) AS total_revenue
        FROM orders AS o
        JOIN order_items AS oi
            USING(order_id)
        WHERE o.order_status = 'delivered'
    ) AS metrics;


---------------------------------------------------------------------------
-- 02. Revenue by Product Category
---------------------------------------------------------------------------

-- Business question:
-- How much revenue is generated by each product category?
--
-- This query groups revenue by the original Portuguese category names
-- stored in the products table.

SELECT 
    p.product_category_name AS category,
    SUM(oi.price) AS revenue

FROM orders AS o
JOIN order_items AS oi
    USING(order_id)
JOIN products AS p
    USING(product_id)

WHERE o.order_status = 'delivered'
GROUP BY category;


-- Business question:
-- How much revenue is generated by each product category using
-- English category names?
--
-- The product_category_translation table is used to translate the
-- Portuguese category names into English.
--
-- The translation table contains 71 categories, while the LEFT JOIN
-- preserves all products from the products table, including categories
-- that have no corresponding translation.
--
-- The result contains 71 translated categories + 1 NULL group
-- (72 rows in total).
--
-- The NULL group here is different because it contains both:
-- 1. Products that actually have a NULL category in the products table.
-- 2. Non-null Portuguese categories with no corresponding translation.

SELECT 
    pct.product_category_name_english AS category,
    SUM(oi.price) AS revenue

FROM orders AS o
JOIN order_items AS oi
    USING(order_id)
JOIN products AS p
    USING(product_id)
LEFT JOIN product_category_translation AS pct
    USING(product_category_name)
    
WHERE o.order_status = 'delivered'
GROUP BY category
ORDER BY revenue DESC;


-- The first query returns 74 rows, while the translated version
-- returns 72 rows.
--
-- This difference suggests that some product categories do not have
-- a corresponding translation.
--
-- The following query identifies those unmatched categories.

SELECT DISTINCT
    p.product_category_name
FROM products AS p
LEFT JOIN product_category_translation AS pct
    USING(product_category_name)
WHERE pct.product_category_name IS NULL
  AND p.product_category_name IS NOT NULL;


-- These two categories exist in the products table but have no
-- corresponding entry in the translation table:
-- "portateis_cozinha_e_preparadores_de_alimentos"
-- "pc_gamer"


---------------------------------------------------------------------------
-- 03. Customer Retention & Repeat Purchases
---------------------------------------------------------------------------

-- Business question:
-- What percentage of customers made more than one delivered purchase?

SELECT 
	customer_type,
	n_customers,
	ROUND((n_customers / SUM(n_customers) OVER() * 100.00),2) AS customer_rate
FROM
	(SELECT 
		CASE WHEN n_orders = 1 THEN 'One Time'
			 ELSE 'Repeat' END AS customer_type,
		COUNT(customer_unique_id) AS n_customers
	
	FROM
		(SELECT
			customer_unique_id,
			COUNT(order_id) as n_orders
		
		FROM customers as c
		JOIN orders as o 
			USING(customer_id)
	
		WHERE o.order_status = 'delivered'
		GROUP BY customer_unique_id
		) AS customer_orders
		
	GROUP BY customer_type
	) AS customers_counts;


-- Only 3% of customers made more than one purchase, indicating
-- a very low repeat-purchase rate and a strong reliance on
-- one-time customers.
--
-- We recommend focusing on customer retention through targeted
-- email marketing and personalized offers to encourage existing
-- customers to make another purchase.


---------------------------------------------------------------------------
-- 04. Seller Revenue Performance
---------------------------------------------------------------------------

-- Business question:
-- Which sellers generate the most revenue?

SELECT 
    seller_id,
    SUM(price) AS total_revenue
FROM order_items
JOIN orders
    USING(order_id)
WHERE order_status = 'delivered'
GROUP BY seller_id
ORDER BY total_revenue DESC;


---------------------------------------------------------------------------
-- 05. Delivery Performance by Region
---------------------------------------------------------------------------

-- Business question:
-- How does delivery performance vary by customer state?

SELECT
    customer_state,
    AVG(o.order_delivered_customer_date - o.order_purchase_ts) AS avg_delivery_time

FROM orders AS o
JOIN customers AS c
    USING(customer_id)

WHERE o.order_status = 'delivered'
GROUP BY customer_state
ORDER BY avg_delivery_time DESC;


---------------------------------------------------------------------------
-- 06. Impact of Late Delivery on Customer Satisfaction
---------------------------------------------------------------------------

-- Business question:
-- Do customers whose orders arrive late give lower review scores?

SELECT 
    CASE WHEN order_delivered_customer_date > order_estimated_delivery_date THEN 'late'
        ELSE 'On Time'
    END AS delivery_time,
    ROUND(AVG(ov.review_score), 2) AS avg_review_score
    
FROM orders AS o
JOIN order_reviews AS ov 
    USING(order_id)

WHERE o.order_status = 'delivered'
GROUP BY delivery_time;


-- Customers whose orders arrived late gave significantly lower
-- review scores than customers whose orders arrived on time.
-- This suggests that late delivery has a strong negative impact
-- on customer satisfaction.


---------------------------------------------------------------------------
-- 07. Most Valuable Geographic Markets
---------------------------------------------------------------------------

-- Business question:
-- Which geographic markets generate the most revenue?

SELECT 
    c.customer_state,
    SUM(oi.price) AS total_revenue

FROM orders AS o
JOIN order_items AS oi
    USING(order_id)
JOIN customers AS c
    USING(customer_id)

WHERE o.order_status = 'delivered'
GROUP BY c.customer_state
ORDER BY total_revenue DESC;


-- São Paulo generates the highest total revenue among Brazilian states,
-- followed by Rio de Janeiro and Minas Gerais.
-- This indicates that these states represent Olist's most important
-- geographic markets in terms of revenue generated from delivered orders.